from lib.Simulations.multiSimulation import multiSimulation
from tensorforce import Agent,Environment
from lib.Simulations.Simulation import Simulation
from lib.plot.plot import Plot

from lib.enviroment.multiAgentEnv.FourLevelTestEnv import FourLevelTestEnv
import pandas as pd
class FourLevelSimulation(multiSimulation):
    def __init__(self):
        self.testResult = {}
        for month in range(12):
            self.testResult[month] = pd.DataFrame()
        self.totalReward = []        
        self.environment = Environment.create(environment = FourLevelTestEnv,max_episode_timesteps=960)
        self.agent = Agent.load(directory = 'HLA/FourLevelAgent/saver_dir',environment=self.environment)
        
    def simulation(self):
        return super().simulation()
    
    def EachMonthResult(self):
        return super().EachMonthResult()

    def avgMonthResult(self):
        return super().avgMonthResult()
            
    def plotTotalResult(self):
        ess = Plot(self.testResult,single=True)
        ess.remainPower(month=5)
        ess.soc(month=5)
        ess.price(month=5)
        ess.plotPgridMax(month=5)
        ess.plotPVPower(month=5)
        ess.plotDeltaSOCPower(month=5)
        ess.plotResult('result/')
        int1 = Plot(self.testResult,single=True)
        int1.remainPower(month=5)
        int1.soc(month=5)
        int1.price(month=5)
        int1.plotPgridMax(month=5)
        int1.plotPVPower(month=5)
        int1.plotIntPreference(1,month=5)
        int1.plotIntLoadPower(1,month=5)
        int1.plotDeltaSOCPower(month=5)
        int1.plotResult('result/')
        int2 = Plot(self.testResult,single=True)
        int2.remainPower(month=5)
        int2.soc(month=5)
        int2.price(month=5)
        int2.plotPgridMax(month=5)
        int2.plotPVPower(month=5)
        int2.plotIntPreference(2,month=5)
        int2.plotIntLoadPower(2,month=5)
        int2.plotDeltaSOCPower(month=5)
        int2.plotResult('result/')
        int3 = Plot(self.testResult,single=True)
        int3.remainPower(month=5)
        int3.soc(month=5)
        int3.price(month=5)
        int3.plotPgridMax(month=5)
        int3.plotPVPower(month=5)
        int3.plotIntPreference(3,month=5)
        int3.plotIntLoadPower(3,month=5)
        int3.plotDeltaSOCPower(month=5)
        int3.plotResult('result/')
        ac1 = Plot(self.testResult,single=True)
        ac1.remainPower(month=5)
        ac1.indoorTemperature(1,month=5)
        ac1.outdoorTemperature(month=5)
        ac1.userSetTemperature(1,month=5)
        ac1.plotHVACPower(id=1,month=5)
        ac1.plotDeltaSOCPower(month=5)
        ac1.price(month=5)
        ac1.plotPgridMax(month=5)
        ac1.plotPVPower(month=5)
        ac1.plotResult('result/')
        ac2 = Plot(self.testResult,single=True)
        ac2.remainPower(month=5)
        ac2.indoorTemperature(2,month=5)
        ac2.outdoorTemperature(month=5)
        ac2.userSetTemperature(2,month=5)
        ac2.plotHVACPower(id=2,month=5)
        ac2.plotDeltaSOCPower(month=5)
        ac2.price(month=5)
        ac2.plotPgridMax(month=5)
        ac2.plotPVPower(month=5)
        ac2.plotResult('result/')
        ac3 = Plot(self.testResult,single=True)
        ac3.remainPower(month=5)
        ac3.indoorTemperature(3,month=5)
        ac3.outdoorTemperature(month=5)
        ac3.userSetTemperature(3,month=5)
        ac3.plotHVACPower(id=3,month=5)
        ac3.plotDeltaSOCPower(month=5)
        ac3.price(month=5)
        ac3.plotPgridMax(month=5)
        ac3.plotPVPower(month=5)
        ac3.plotResult('result/')
        unint1= Plot(self.testResult,single=True)
        unint1.remainPower(month=5)
        unint1.soc(month=5)
        unint1.price(month=5)
        unint1.plotPgridMax(month=5)
        unint1.plotPVPower(month=5)
        unint1.plotUnintPreference(1,month=5)
        unint1.plotUnIntLoadPower(1,month=5)
        unint1.plotResult('result/')
        unint2 = Plot(self.testResult,single=True)
        unint2.remainPower(month=5)
        unint2.soc(month=5)
        unint2.price(month=5)
        unint2.plotPgridMax(month=5)
        unint2.plotPVPower(month=5)
        unint2.plotUnintPreference(2,month=5)
        unint2.plotUnIntLoadPower(2,month=5)
        unint2.plotResult('result/')       




    def outputResult(self,mode):
        output = Plot(self.testResult)
        if mode == "hvac":
            output.remainPower()
            output.soc()
            output.indoorTemperature(1)
            output.indoorTemperature(2)
            output.indoorTemperature(3)
            output.outdoorTemperature()
            output.userSetTemperature(1)
            output.userSetTemperature(2)
            output.userSetTemperature(3)
            output.plotHVACPower(id=1)
            output.plotHVACPower(id=2)
            output.plotHVACPower(id=3)
            output.plotDeltaSOCPower()
            output.price()
            output.plotPgridMax()
            output.plotPVPower()
            output.plotResult('lib/plot/FourLevel/hvac/')

        elif mode == "soc":
            output.remainPower()
            output.soc()
            output.price()
            output.plotPgridMax()
            output.plotPVPower()
            output.plotDeltaSOCPower()
            output.plotResult('lib/plot/FourLevel/soc/')
            
        elif mode == "int":
            output.remainPower()
            output.soc()
            output.price()
            output.plotPgridMax()
            output.plotPVPower()
            output.plotIntPreference(1)
            output.plotIntPreference(2)
            output.plotIntPreference(3)
            output.plotIntLoadPower(1)
            output.plotIntLoadPower(2)
            output.plotIntLoadPower(3)
            output.plotDeltaSOCPower()
            output.plotResult('lib/plot/FourLevel/int/')

        elif mode == "unint":
            output.remainPower()
            output.soc()
            output.price()
            output.plotPgridMax()
            output.plotPVPower()
            output.plotUnintPreference(1)
            output.plotUnintPreference(2)
            output.plotUnIntLoadPower(1)
            output.plotUnIntLoadPower(2)
            output.plotResult('lib/plot/FourLevel/unint/')
        else:
            output.remainPower()
            output.soc()
            output.price()
            output.plotPgridMax()
            output.plotPVPower()
            output.plotDeltaSOCPower()
            output.plotHVACPower(id=1)
            output.plotHVACPower(id=2)
            output.plotHVACPower(id=3)
            output.plotIntPreference(1)
            output.plotIntPreference(2)
            output.plotIntPreference(3)
            output.plotIntLoadPower(1)
            output.plotIntLoadPower(2)
            output.plotIntLoadPower(3)
            output.plotUnintPreference(1)
            output.plotUnintPreference(2)
            output.plotUnIntLoadPower(1)
            output.plotUnIntLoadPower(2)
            output.plotResult('lib/plot/FourLevel/')

    def __del__(self):
        return super().__del__()
    
